# Generated by Django 3.1.5 on 2021-02-20 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20210122_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meetingtime',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='meetingminutes',
            name='minutes',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='meetingminutes',
            table='meetingminutes',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='TechType',
        ),
    ]
